//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactU.Models
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// The concrete model.
    /// </summary>
    public partial class Contact
    {
        public int ContactId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public byte[] Image { get; set; }

        public Contact()
        {

        }

        public Contact(int contactId, string firstName, string lastName, string mobile, string email, byte[] image)
        {
            this.ContactId = contactId;
            this.FirstName = firstName;
            this.LastName = lastName;
            this.Mobile = mobile;
            this.Image = image;
        }

        
    }
}
